### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#310]
Hello,
Following the instructions for Mac, I tried to install freefeed-server on my local Ubuntu machine. 

Apart from the database creation, the rest seemed quite strightforward. 

But at the end of the installation, when running `npm test` I get:

```
me@pc:~/freefeed-server$ npm test

> freefeed-server@1.45.0 test /home/me/freefeed-server
> run-s reset-test-db test-rollback mocha


> freefeed-server@1.45.0 reset-test-db /home/me/freefeed-server
> babel-node bin/clean_test_db && knex --env test migrate:latest

Error: error: password authentication failed for user "postgres"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freefeed-server@1.45.0 reset-test-db: `babel-node bin/clean_test_db && knex --env test migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freefeed-server@1.45.0 reset-test-db script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2018-04-26T01_51_13_577Z-debug.log
ERROR: "reset-test-db" exited with 1.
npm ERR! Test failed.  See above for more details.
```
 

What I did was to create a user and database both called `freefeed` with password `freefeed` while I logged in to postgre shell. Is that correct?
  
 If so what could have gone wrong in my installation?

**Comment by indeyets** [comment]
1. Knexfile has separate section for tests db-access. Make sure that it has valid credentials
2. This is irrelevant to current issue, but we really-really suggest to use yarn instead of npm. Will save you from some gray hair later on

**Comment by k0fi** [comment]
Thanks for the tip. I changed the username/password of `test` in `knexfile.js` and the problem is resolved. 
I think this should be mentioned in the docs to avoid similar confusions. 

Apart from that I run the test, and got a failure, that might  be interesting to know for the devs.
```
  1 failing

  1) BookmarkletController
       #create()
         should create post in the multiple feeds:
     UnexpectedError: 
expected
[
  { id: 'f0daacaf-2d25-42d6-8d35-5efaa5700b78', name: 'Posts', user: 'd7b08c09-c859-4053-855f-1b422736bbf7' },
  { id: '516df295-c660-4e47-bf93-8208b7eddcc1', name: 'Posts', user: 'cbe70e60-2fa5-4469-a633-56877060a3f7' }
]
to satisfy [ { name: 'Posts', user: 'cbe70e60-2fa5-4469-a633-56877060a3f7' }, { name: 'Posts', user: 'd7b08c09-c859-4053-855f-1b422736bbf7' } ]

[
  {
    id: 'f0daacaf-2d25-42d6-8d35-5efaa5700b78',
    name: 'Posts',
    user: 'd7b08c09-c859-4053-855f-1b422736bbf7' // should equal 'cbe70e60-2fa5-4469-a633-56877060a3f7'
                                                 //
                                                 // d7b08c09-c859-4053-855f-1b422736bbf7
                                                 // cbe70e60-2fa5-4469-a633-56877060a3f7
  },
  {
    id: '516df295-c660-4e47-bf93-8208b7eddcc1',
    name: 'Posts',
    user: 'cbe70e60-2fa5-4469-a633-56877060a3f7' // should equal 'd7b08c09-c859-4053-855f-1b422736bbf7'
                                                 //
                                                 // cbe70e60-2fa5-4469-a633-56877060a3f7
                                                 // d7b08c09-c859-4053-855f-1b422736bbf7
  }
]

      at Context.<anonymous> (test/functional/bookmarklet.js:56:7)
      at Generator.next (<anonymous>)
      at Generator.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freefeed-server@1.45.0 mocha: `cross-env NODE_ENV=test mocha --opts test/mocha.opts test/unit test/functional`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freefeed-server@1.45.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2018-04-26T07_57_02_773Z-debug.log
ERROR: "mocha" exited with 1.
npm ERR! Test failed.  See above for more details.
```

 I have no idea how crucial is this failure. Appreciat your clarification.

**Comment by indeyets** [comment]
@k0fi thanks for heads up. it was an issue with test, not with code. fixed now
